apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue-deployment
  namespace: roboshop
  labels:
    tier: app
    name: catalogue
spec:
  replicas: {{ .Values.deploymentset.replicaCount }}
  selector:
    matchLabels:
      tier: app
      name: catalogue
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        tier: app
        name: catalogue
    spec:
      containers:
      - name: catalogue
        imagePullPolicy: Always
        image: "573314280082.dkr.ecr.ap-south-1.amazonaws.com/catalogue:{{ .Values.deploymentset.imageVersion }}"
        envFrom:
        - configMapRef:
            name: catalogue-config
        ports:
        - containerPort: 8080
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: catalogue-hpa  # Updated name for HPA
  namespace: roboshop
  labels:
    tier: app
    name: catalogue
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: catalogue-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
